[project]
name = "pdfimgconverter"
version = "0.1.0"
description = "图片转PDF,PDF转图片"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["img2pdf>=0.5.0", "pdf2image>=1.17.0", "Pillow>=10.0.0"]
